kind: pipeline
type: docker
name: default

steps:
- name: build image
  image: plugins/docker
  settings:
    username: iami
    password: 
      from_secret: registry_password
    registry: atlas.iami:5000
    repo: atlas.iami:5000/the_past
    cache_from: atlas.iami:5000/the_past
    insecure: true
    mirror: https://n982qycn.mirror.aliyuncs.com
- name: deploy image
  image: docker/compose
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  - name: docker_compose
    path: /home/docker
  commands:
  - ls -la /home/docker
  - docker-compose -f /home/docker/live/docker-compose.yaml pull the_past 
  - docker-compose -f /home/docker/live/docker-compose.yaml up -d the_past
- name: Notification
  image: atlas.iami:5000/drone_notification_bot
  when:
    status:
    - failure
    - success
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_compose
    host:
      path: /home/iami/docker